[package]
name = "nexon-open-api-proxy"
version = "0.1.0"
edition = "2021"
authors = ["psvm203 <psvm203@proton.me>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6" }
worker-macros = { version = "0.6" }
console_error_panic_hook = { version = "0.1.7" }
